services:
  api:
    build:
      context: ./TicketBriteAPI
      dockerfile: Dockerfile
    ports:
      - "7150:7150"
    container_name: Ticketbrite-api
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=TicketBrite-database,1433;Database=TicketBrite;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
      - SQL_SERVER=sqlserver-container
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./TicketBrite
      target: prod
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    container_name: Ticketbrite-frontend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TicketBrite-database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data: {}