services:
  api:
    build:
      context: .
      dockerfile: TicketBriteAPI/Dockerfile
    ports:
      - "7150:7150"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TicketBrite;User=sa;Password=Password123;
    depends_on:
      - db

  # React Frontend
  frontend:
    build:
      context: .
      dockerfile: TicketBrite/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

  # SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  # Cypress Test Runner
  cypress:
    image: cypress/included:12.0.0
    environment:
      - CYPRESS_baseUrl=http://frontend:5173
    depends_on:
      - frontend
    entrypoint: ["npx", "cypress", "run"]
    volumes:
      - ./cypress:/e2e
    working_dir: /e2e

volumes:
  db_data:
