version: '3.8'
services:
  api:
    build:
      context: ./TicketBriteAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=TicketBriteDB;User Id=sa;Password=YourPassword123;
    depends_on:
      - db

  frontend:
    build:
      context: ./TicketBrite
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  db:
   image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticketbrite_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

