services:
  api:
    build:
      context: ./TicketBriteAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver-container,1433;Database=TicketBrite;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./TicketBrite
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data: {}
