name: TicketBrite CI Pipeline

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op
      - name: Checkout code
        uses: actions/checkout@v4

      # Stap 2: Log in op Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Stap 3: Build Docker Images (via jouw Dockerfiles)
      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite-api -f ./TicketBriteAPI/Dockerfile ./TicketBriteAPI
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite-frontend -f ./TicketBrite/Dockerfile ./TicketBrite

      # Stap 4: Start de services met jouw docker-compose.yml
      - name: Start services
        run: docker compose -f ./docker-compose.yml up -d

      # Stap 6: Voer Cypress-tests uit
      - name: Run Cypress tests
        working-directory: ./TicketBrite
        run: npx cypress run

      # Stap 7: Stop en verwijder de services
      - name: Stop services
        run: docker compose -f ./docker-compose.yml down
