name: TicketBrite CI Tests

# wordt uitgevoerd bij push en pull request van de main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./TicketBriteAPI/TicketBriteAPI.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./TicketBriteAPI/TicketBriteAPI.csproj --no-restore --verbosity normal

