name: TicketBrite CI Pipeline

on:
  push:
    branches:
      - main
      - CI/CD
      - CI/CD-http
      - CI/CD-2
  pull_request:
    branches:
      - main
      - CI/CD

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  

    - name: Build and start containers
      run: |
        docker-compose up --build -d

    - name: Run unit tests
      run: |
        docker exec api dotnet test

    - name: Run Cypress tests
      run: |
        docker exec cypress npx cypress run

    - name: Shut down Docker containers
      run: |
        docker-compose down