name: TicketBrite CI Tests

# Wordt uitgevoerd bij push en pull request van de main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./TicketBriteAPI/TicketBriteAPI.sln  # Restore vanuit de API map

      - name: Build
        run: dotnet build ./TicketBriteAPI/TicketBriteAPI.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./TicketBriteAPI/TicketBriteAPI.sln --no-restore --verbosity normal

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-test  # Wacht op voltooiing van unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./TicketBrite  # Zorg dat dit je frontend-map is
        run: npm ci

      - name: Start services
        run: docker-compose up -d
        env:
          DB_PASSWORD: YourPassword123  # Zorg dat de juiste omgevingsvariabelen beschikbaar zijn

      - name: Wait for API and Frontend
        run: npx wait-on http://localhost:5000 http://localhost:3000

      - name: Run Cypress tests
        working-directory: ./TicketBrite
        run: npx cypress run

      - name: Stop services
        run: docker-compose down
