name: TicketBrite CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers with Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml up --build -d

      - name: Run .NET Core tests
        run: |
          docker-compose exec api dotnet test ./TicketBriteAPI/TicketBriteAPI.sln --no-restore

      - name: Run Cypress tests
        run: |
          docker-compose exec cypress npx cypress run --headless --no-exit

      - name: Shut down containers
        run: |
          docker-compose down
