name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Debug values
        run: |
          echo "DockerHub Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Git SHA: ${{ github.sha }}"
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite:${{ github.sha }}

      # Optionally, add a 'latest' tag and push
      - name: Tag Docker Image as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticketbrite:latest
